version: 2
jobs: # can define different jobs, such as 'build', 'test', 'deploy'
  build:
    docker: # define the docker containers you want, for browsers, suffix '-browsers', to have the image run in memory, use '-ram', etc.
      - image: circleci/node:10-browsers # primary container, the commands in 'steps' execute on this, additional images are run as docker containers

    working_directory: ~/repo
    steps:
      - checkout # checkout the repo branch
      - restore-cache: # detect if you need to update the dependency cache, steps from here until 'save_cache' will only run if they are different. Since this is a nodejs project we'll do this with checksum of package file
          key: dependency-cache-{{ checksum "package.json" }}
      - run: # run a command, this one installs the dependencies
          name: install
          command: npm install
      - save_cache: # if you needed to update the cache, save it for next run
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts: # store anything by-products in a folder
          path: coverage/
          prefix: coverage/
      - store_test_results: # store the test results in a folder
          path: tmp/test-results/

  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: deploy master branch
          command: echo "Deployed!"

workflows: # allows for running multiple jobs sequentially
  version: 2
  build-test-deploy: # give a name to the workflow
    jobs: # list the jobs you want in it
      - build
      - deploy:
          requires: # makes sure things run in the right order
            - build
          filters: # makes sure the job is only executed in specific cases
            branches:
              only: master
